### ISSUE TITLE
Не печатает принтер

### ISSUE THREAD

**Issue by ZAZmaster** [GraninDB/TCPPrintService#4]
Установил вашу программу, подключил принтеры, отправляю на печать, на клиенте вижу в очереди печати что уходит, на "сервере" вижу что появляется в очереди печати и пропадает, но принтер молчит. В логе всё хорошо, ошибок нет, видно что задания приходят и отправляются на печать. На клиентах win7 на "сервере" win10, принтер HP LJ M104a.

**Comment by GraninDB** [comment]
У пользователя проблема решилась переустановкой драйверов на принтер.
